### ISSUE TITLE
Most options missing?

### ISSUE THREAD

**Issue by KeynxKen** [ManlyMarco/IllusionCheatTools#27] opened 2024-06-13 20:12 UTC
![image](https://github.com/ManlyMarco/IllusionCheatTools/assets/172651574/9e2bccdc-938f-4780-ad52-822d3066c36a)

**Comment by KeynxKen** [comment] 2024-06-13 20:13
Also checked on version 3.3.2, downgraded to see if it the latest version was the issue.

**Comment by takahiro0327** [comment] 2024-06-14 07:49
That screen is normal with it in the plugin settings.
The cheat tool can be called from the leftmost button in UnityRuntimeEditor.
The UnityRuntimeEditor can be called with the Pause key in my environment, which is the key in the settings in the second screenshot.
Close the issue when the problem is solved.
![image](https://github.com/ManlyMarco/IllusionCheatTools/assets/4230203/93aea1ee-6f4e-4470-b640-0b32d3524617)
![image](https://github.com/ManlyMarco/IllusionCheatTools/assets/4230203/b6bcfa16-13ed-4049-b088-58d7b1def3ab)

**Comment by ManlyMarco** [comment] 2024-06-15 15:33
Make sure both CheatTools and RuntimeUnityEditor are both up to date.

**Comment by takahiro0327** [comment] 2024-06-16 01:40
The only plugin configuration item in KKS is noclip, right?
https://github.com/search?q=repo%3AManlyMarco%2FIllusionCheatTools%20ConfigEntry&type=code

**Comment by ManlyMarco** [comment] 2024-06-17 12:34
> The only plugin configuration item in KKS is noclip, right?

Yes.

**Closed** 2024-09-22 00:51 UTC
